### PR TITLE
[Review] Request from 'schubi2' @ 'yast/yast-schema/review_151006_spec_is_opensuse'

### PR DESCRIPTION
**Pull request by schubi2**
Please review the following changes:
  * 27185f1 packaging
  * 1effe94 taking proper is_opensuse

### CODE REVIEW

**Comment by ancorgs** [comment]
LGTM, although packaging is not my strong point

**Comment by mvidner** [comment]
@schubi2 @coolo I wonder where this is <s>docum</s> defined? I don't see `is_opensuse` in https://build.opensuse.org/package/view_file/openSUSE:Factory/rpm/rpm-suse_macros?expand=1

**Comment by mvidner** [comment]
Er, now I have seen https://build.opensuse.org/project/prjconf/openSUSE:Factory . My eyes!

**Comment by mvidner** [comment]
And the documentation seems to be [this email](http://lists.opensuse.org/opensuse-factory/2015-06/msg00238.html).

**Pull request merged**
